version: "3"

services:
  mysql:
    image: mysql
    container_name: mercafacil_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/mysqlData:/var/lib/mysql

  postgresql:
    image: postgres
    container_name: mercafacil_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: admin
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
    volumes:
      - ./db/postgresData:/data/postgres
#  mercafacil_api:
#      build: ./api
#      container_name: mercafacil_api
#      ports:
#          - 3333:3333
#      volumes:
#          - ./api:/usr/app
